export type TypedArray = Int8Array | Uint8Array | Uint8ClampedArray | Int16Array | Uint16Array | Int32Array | Uint32Array;
export type Encoding = "base2" | "binaryString" | "binary" | "latin1" | "base16" | "hex" | "base64" | "ascii" | "base64Url" | "asciiUrl" | "windows1252" | "windows-1252" | "utf16" | "utf-16" | "utf8" | "utf-8";
export declare function typedArrayToUint8Array(typedArray: TypedArray): Uint8Array;
export declare function stringToTypedArray(str: string, encoding: Encoding): Uint8Array;
export declare function typedArrayToString(typedArray: TypedArray, encoding: Encoding): string;
export declare function binaryToTypedArray(binary: string): Uint8Array;
export declare const latin1ToTypedArray: typeof binaryToTypedArray;
export declare function binaryStringToTypedArray(binary: string): Uint8Array;
export declare function hexToTypedArray(hex: string): Uint8Array;
export declare function asciiToTypedArray(ascii: string): Uint8Array;
export declare const base64ToTypedArray: typeof asciiToTypedArray;
export declare function asciiUrlToTypedArray(asciiUrl: string): Uint8Array;
export declare const base64UrlToTypedArray: typeof asciiUrlToTypedArray;
export declare function windows1252ToTypedArray(string: string): Uint8Array;
export declare function utf16ToTypedArray(string: string): Uint8Array;
export declare function utf8ToTypedArray(string: string): Uint8Array;
export declare function typedArrayToBinary(typedArray: TypedArray): string;
export declare const typedArrayToLatin1: typeof typedArrayToBinary;
export declare function typedArrayToBinaryString(typedArray: TypedArray): string;
export declare function typedArrayToAscii(typedArray: TypedArray): string;
export declare const typedArrayToBase64: typeof typedArrayToAscii;
export declare function typedArrayToAsciiUrl(typedArray: TypedArray): string;
export declare const typedArrayToBase64Url: typeof typedArrayToAsciiUrl;
export declare function typedArrayToHex(typedArray: TypedArray): string;
export declare function typedArrayToWindows1252(typedArray: TypedArray): string;
export declare function typedArrayToUtf16(typedArray: TypedArray): string;
export declare function typedArrayToUtf8(typedArray: TypedArray): string;
export declare function convertEncoding<T extends string | TypedArray>(value: T, encodingSource: Encoding, encodingOutput: Encoding): T extends string ? string : Uint8Array;
//# sourceMappingURL=index.d.ts.map